### ISSUE TITLE
Build failed in Travis CI.    (Works fine on desktop)

### ISSUE THREAD

**Issue by jmschrack** [gfscott/eleventy-plugin-youtube-embed#14]
TravisCI throws the following error when it tries to build:
```
`SyntaxError` was thrown:
    SyntaxError: Invalid regular expression: /<p>(\s*)(<a(.*)>)?(\s*)(https?:\/\/)?(w{3}\.)?(youtube\.com|youtu\.be)\/(watch\?v=|embed\/)?(?<videoId>[A-Za-z0-9-_]{11})(\S*)(\s*)(<\/a>)?(\s*)<\/p>/: Invalid group
        at extractVideoId (/home/travis/build/jmschrack/jmschrack.github.io/node_modules/eleventy-plugin-youtube-embed/.eleventy.js:35:25)
        at /home/travis/build/jmschrack/jmschrack.github.io/node_modules/eleventy-plugin-youtube-embed/.eleventy.js:20:21
        at Array.forEach (<anonymous>)
        at Template.eleventyConfig.addTransform (/home/travis/build/jmschrack/jmschrack.github.io/node_modules/eleventy-plugin-youtube-embed/.eleventy.js:19:13)
        at Template.runTransforms (/home/travis/build/jmschrack/jmschrack.github.io/node_modules/@11ty/eleventy/src/Template.js:387:29)
        at Template.renderPageEntry (/home/travis/build/jmschrack/jmschrack.github.io/node_modules/@11ty/eleventy/src/Template.js:539:28)
        at <anonymous>
        at process._tickCallback (internal/process/next_tick.js:189:7)
```

However, running eleventy locally works fine with no issues.

**Comment by gfscott** [comment]
Hm. It looks like maybe Travis doesn’t accept [named capture groups](https://github.com/tc39/proposal-regexp-named-groups) in regex, so it’s failing on the `?<videoId>` value.

I'll look into Travis (I haven't used it much) and consider some alternative approaches. Thanks for filing an issue!

**Comment by gfscott** [comment]
@jmschrack So I [made a PR today](https://github.com/gfscott/eleventy-plugin-youtube-embed/pull/15) to try to address this. I took the liberty of forking your repo and running it through Travis, and the build passed this time:

https://travis-ci.org/github/gfscott/jmschrack.github.io/jobs/662532397

If you're able, it would be great to confirm that this update is working for you before I merge it. If you could [pull that branch](https://github.com/gfscott/eleventy-plugin-youtube-embed/tree/destructuring-instead) and give it a try yourself, I'd be obliged. 🙏 

As I suspected, the problem is the named capture groups, which were only added to Node with version 10. Since your build is set to use Node 8, those RegExes wouldn't work. Seems better to just use a more widely supported method, rather than requiring Node 10.
